### PR TITLE
Implement mutable metdata trait from Arnavion/k8s-openapi#67

### PR DESCRIPTION
**Pull request by ctron**
This implements the new mutable function from Arnavion/k8s-openapi#67.

It allows to set the metadata of a CRD, without needing the exact type, used to create a `create_or_update` function:

~~~rust
    async fn create_or_update<T, F>(
        &self,
        api: &Api<T>,
        namespace: String,
        name: String,
        mutator: F,
    ) -> Result<()>
    where
        T: Clone + Serialize + DeserializeOwned + Meta<Ty = ObjectMeta> + Default,
        F: FnOnce(T) -> Result<T>,
    {
        match api.get(&name).await {
            Err(Error::Api(ae)) if ae.code == 404 => {
                log::info!("CreateOrUpdate - Err(Api(404))");
                let mut object: T = Default::default();
                object.set_metadata(ObjectMeta {
                    namespace: Some(namespace),
                    name: Some(name),
                    ..Default::default()
                });
                let object = mutator(object)?;
                api.create(&PostParams::default(), &object).await?;
            }
            Err(e) => {
                log::info!("Error - {}", e);
                Err(e)?;
            }
            Ok(object) => {
                log::info!("CreateOrUpdate - Ok(...)");
                let object = mutator(object)?;
                api.replace(&name, &PostParams::default(), &object).await?;
            }
        };

        Ok(())
    }
~~~

### CODE REVIEW

**Comment by teozkr** [comment]
Not sure I see the use-case for this.. can't you just flip it and take an object that must already have `name` (and `metadata`) set? I'm not a huge fan of all the Option-unwrapping, but 

Speaking of namespaces.. your code has a few other bugs around them: the `Api::get` call doesn't respect the supply namespace, and it doesn't understand cluster-scoped types at all.

**Comment by ctron** [comment]
> Not sure I see the use-case for this.. can't you just flip it and take an object that must already have `name` (and `metadata`) set? 

The use case it to create a simple reconcile loop, e.g:

~~~rust
create_or_update(&self.deployments, namespace, name, |obj| {
  self.reconcile_concierge_deployment(mycrd, obj)
})

fn reconcile_concierge_deployment(&self, mycrd: &MyCrd, mut deployment: Deployment ) -> Result<Deployment> {…}
~~~

So that you can get the current state of a derived resource, modify it, (possibly to a compare) and store.

> I'm not a huge fan of all the Option-unwrapping, but

I don't like all the Option wrapping either, but I think that is was is being created by `k8s-openapi`.

> 
> Speaking of namespaces.. your code has a few other bugs around them: the `Api::get` call doesn't respect the supply namespace, and it doesn't understand cluster-scoped types at all.

So yes, this function currently requires a namespaced resource. Unfortunately the `get` method doesn't allow for getting with a (namespace/name) pair. But it works as expected, as long as you put in the same namespace as the Api was created with.

I think the situation could be improved if the `Api` could return the namespace it was constructed with.

**Comment by ctron** [comment]
The Go version of that, as a reference: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L192

**Comment by ctron** [comment]
This has been addressed differently in k8s-openapi 0.9.0.

**Comment by clux** [comment]
Ah cool. Have you got a link?

**Comment by ctron** [comment]
This has already been addressed by https://github.com/clux/kube-rs/commit/a839081a4199bb1c60d83a46ea37a09908511699 

Specifically: https://github.com/clux/kube-rs/commit/a839081a4199bb1c60d83a46ea37a09908511699#diff-556f20a8dced0e7d6127470f636e89b5R303-R307

Looking forward to a new release soon :grimacing:

**Comment by clux** [comment]
Yeah. It's coming today. Theo fixed all the Sync issues we had with integrating kube-runtime elsewhere.

**Pull request closed without merging**
