### PR TITLE
Link PR and Issue references in CHANGELOG.MD

### PR DESCRIPTION
**Pull request by praveenperera**

### CODE REVIEW

**Review by clux — APPROVED** [review]
thanks!
did you do this with a script? it's almost worth adding to the prerelease script that does search and replace on that file already.

**Comment by praveenperera** [comment]
Yes @clux, I wrote a little rust script. I've cleaned it up a little and made it public: https://github.com/praveenperera/linker

**Comment by clux** [comment]
Awesome. Thank you. I'll probably repose that a bit if you don't mind :-)

**Comment by praveenperera** [comment]
Ya for sure feel free to use whatever parts you need

**Comment by clux** [comment]
Ended up doing the dumber thing with `sd` instead because all the rest of my release logic is in the shell script already (thankfully github redirect saved me if it's actually a pull and not an issue). But used the same regex idea :-)

**Pull request merged**
