### PR TITLE
comment dbg!(..)

### PR DESCRIPTION
**Pull request by davidB**
Sorry I left a dbg!(...) in the code for oidc support.

### CODE REVIEW

**Comment by detro** [comment]
Yeah, I noticed it. I was going to open a PR to remove it but you beat me to it :)

**Comment by davidB** [comment]
Can you make a 0.17.1 release ? (sorry)

**Comment by clux** [comment]
You know you can pin to a git sha, right? I'll have to do it later.

**Comment by detro** [comment]
> You know you can pin to a git sha, right? I'll have to do it later.

Nope. I didn't know. https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

Learned a new thing today :)

**Comment by davidB** [comment]
Yes, but iirc we can not publish on crate.io with git dependencies. I'll try (after fixing some other issue to match requirement for kubectl krew).

Thanks

**Comment by clux** [comment]
0.17.1 released now.

**Comment by detro** [comment]
Thank you and, just because in open source is frequently omitted, THANK YOU SO MUCH.
This project has been so far a pleasure to work with.

**Pull request merged**
