### PR TITLE
Tokio 1.0

### LINKED ISSUE #339: tokio 1.0
Just a tracking issue for the tokio 0.3 upgrade.

A couple of things needed;

- [x] minor changes in [tokio::time](https://docs.rs/tokio/0.3.3/tokio/time/index.html) for old runtime (if we care anymore)
- [ ] `reqwest` needs to bump it https://github.com/seanmonstar/reqwest/issues/1060 (it's in their master, you can use patch (see below), but a kube release blocked on a crates release of `reqwest`)

### PR DESCRIPTION
**Pull request by teozkr**
Fixes #339

Currently uses an unreleased reqwest, since this requires https://github.com/seanmonstar/reqwest/pull/1076

### CODE REVIEW

**Comment by clux** [comment]
Nice work. Looks all fine to me.

Though; since we can't release it until reqwest is released properly, maybe we wait with merging this until #360 is in before merging? @kazk already has a ton of `Cargo.toml` modifications there, and don't want to make that pr any harder than it already is.

**Comment by kazk** [comment]
I tried rebasing #360 from this. It's doable, but I had to resolve merge conflicts multiple times for `Cargo.toml`, so merging that first will be cleaner.

To make #360 compile, I had to

- update versions of TLS crates
- update `async-tungstenite` to v0.11.0
- replace `tokio::io::reader_stream()` with `tokio_util::io::ReaderStream::new()` after adding `tokio-util = { version = "0.6.0", features = ["io"], optional = true }` and updating `ws = ["async-tungstenite", "tokio-util"]` feature

I'll do a follow-up PR after these two are merged to clean up some things (e.g., using re-exported `native-tls` and finish `rustls` support).

**Comment by clux** [comment]
There's still files marked as conflicting here, I can merge if you want to fix them up.

**Comment by teozkr** [comment]
Merged latest master now. Something still seems to be borked around tungstenite+rustls though.

**Comment by clux** [comment]
Well, there were a few follow-up things on that. Tests are at the very least green. I'll merge this one to let people use this as a patch branch.

**Pull request merged**
