### PR TITLE
Import kube-rt tree

### PR DESCRIPTION
**Pull request by clux**
A WIP import that aims to get to point 1 of https://github.com/clux/kube-rs/issues/148#issuecomment-629411640

Marking down some key points:

- [x] [imported kube-rt codebase](https://gitlab.com/teozkr/kube-rt) (with `git subtree add -P kube-runtime git@gitlab.com:teozkr/kube-rt.git master`
- [x] made it work as part of workspace with joint examples dir
- [x] consolidate dev-deps
~~- [ ] migrate from kube-runtime to kube/src/runtime or kube/src/runtime2~~ - deprecate old runtime first

The latter migration requires consolidating the normal dependencies and dealing with some unpublishable things:

- [x] deal with pin-cell git dependency - cannot just use 0.1.1 due to:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-cell-0.1.1/src/lib.rs:3:1
  |
3 | #![feature(pin, arbitrary_self_types)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

- [x] deal with #[project] deprecated attr warning #259

- ~~[ ] unify error handling (move to snafu + inside kube + color_eyre inside examples)~~ can be done if the crates are properly  united
- [ ] migrate examples from old runtime to new runtime (might save some of these for later so we can do a migration release)

Maybe try to also get examples as a top level directory. Tried that before, but it was [slightly annoying with workspaces](https://github.com/rust-lang/cargo/issues/7467)

### CODE REVIEW

**Comment by clux** [comment]
Now that watcher/reflector have replaced Reflector/Informer in a couple of example, the final focus now is getting `controller` **easy-to-use** and **publishable**:

It's not **publishable** atm due to `pin-utils`, and that part of the logic is very complicated and intimidating to read. Ideally we should use something like [stream::split](https://docs.rs/futures/0.3.5/futures/stream/trait.StreamExt.html#method.split) and some kind of `map_ok`, but I'm guessing the reason for what we have now is `Pin` restrictions, and haven't really understood that part at all yet.

As for **easy-to-use** part; while the inner design is really nice, it does not really hide much of the complexity (had to read most of controller.rs to understand configmapgen_controller). I'm thinking it **might be possible** to create a more "easy-mode" `Controller` type that **wraps** `controller` and sets a couple of defaults. `Controller` would:

- own the underlying reflector
- deal with the store (maybe pass it around in a reconciler context)
- main object type always hooked up in queue as `trigger_self(try_flatten_touched(`
- .owns() builder that always ensures it's hooked up via `trigger_owners(try_flatten_applied(`
- comes with a default error handling policy of 120 seconds requeue

Also think that a context argument to the reconciler should help the fn being lifted out of a big lambda in the middle of `main`.

**Comment by clux** [comment]
The last of my core-goals from last week's comment are actually achieved now. Probably going to merge this on the weekend. `Controller<K>` have [this architecture internally](https://edotor.net/?engine=dot#digraph%20G%20%7B%0A%20%20%20%20subgraph%20cluster_ControllerBuilder%20%7B%0A%20%20%20%20%20%20%20%20label%20%3D%20ControllerBuilder%0A%20%20%20%20%20%20%20%20watcher%20-%3E%20reflector%20-%3E%20Store%20-%3E%20controller%0A%20%20%20%20%20%20%20%20reflector%20-%3E%20trigger%20-%3E%20controller%0A%20%20%20%20%7D%0A%20%20%20%20controller%20-%3E%20reconciler%20-%3E%20controller%0A%20%20%20%20controller%20-%3E%20error_policy%20-%3E%20controller%0A%7D%0A) and is largely a builder front for Theo's `controller` (which I've provisionally renamed to `applier`).

Not sure whether to smash all the crates together into one super-crate or, I know that was the plan, but starting to think that maybe there's a benefit to having the boundaries outside the crate level for #204 . Plus, it also lets us have one kube release that's a proper migration release where people can switch over.

Regardless, will start porting over most of the examples later.

**Comment by teozkr** [comment]
:+1: from me on separate crates.

**Comment by praveenperera** [comment]
Congrats on this huge merge guys @clux & @teozkr

Very nice work! I’m excited to try the controller out. 

It’s going to make it so much easier to build what i’m building!  

Thanks!

**Pull request merged**
