### PR TITLE
kube-derive experimentation

### PR DESCRIPTION
**Pull request by clux**
For #159

This might not be the way to go, but at least it's a way to learn how to do proc-macros. It's daunting to try and fix stuff in the existing `k8s-openapi-derive` crate, but might still do that.

For now, this serves as failing tests. We've ripped out everything but arg parsing from the original crate. We don't need api integration with `k8s_openapi`, nor the swagger validation at the moment, but would like a more kubebuilder like setup (but typesafe).

Some open questions;

- should we enforce you generate the root type of a FooSpec?
- if FooSpec then howto FooStatus
- would be nice to not have the root type opaque..
- How to access the generated CRD (so we can install it)? trait CRD+ impl via derive on root obj?
- use inflector library to infer plural? seems to work well so far..

- how about openapi validation? the existing codegen for it was... intense. but it would be nice to have, at laest if the [crd](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/)  can derive the [latest structural schema types](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/) - however might have better solns via 
#129

Then the two things we defo have to do:

- `impl k8s_openapi::Resource` for the root type
- `impl k8s_openapi::Metadata<Ty=ObjectMeta>` for the root type

NB: based on [k8s-openapi-derive](https://arnavion.github.io/k8s-openapi/v0.7.x/k8s_openapi_derive/derive.CustomResourceDefinition.html) ([src](https://github.com/Arnavion/k8s-openapi/tree/master/k8s-openapi-derive/src))

### CODE REVIEW

**Comment by clux** [comment]
Ok.. I have tried to do some [kubebuilder like hacks](https://book.kubebuilder.io/reference/generating-crd.html#additional-printer-columns). Probably need to find something better because it's super gross.

We currently still follow the derive approach where we implicitly create the root object. I'm still not sure about this:
- makes it super magic
- no way to control visibility of it (unless we re-use visibility modifiers from FooSpec)

however, it means people:
- can't get the spec/status convention wrong
- won't need ObjectMeta in scope

For making the crd, we currently implement a `Foo::crd` method straight on the magic type. This allows people do do with it what they want... serialize it, post it to k8s via `Api<Foo>`.

The `crd_api` example actually fully works for v1beta1 api (which i set with a `#[kube(unstable)]` attr. maybe we should use an explicit `#[kube(crd = "v1beta1")]` instead.

Haven't gotten to test the stable one, but that's what I based my coding on.

**Comment by clux** [comment]
One thing worth considering; the `CustomResource` derive could be split into 2-3 other derives:

- `#[derive(CustomResource)]` -> creates `Foo` + `impl k8s_openapi::Resource for Foo`
   * requiring #[custom_resource(group = "clux.dev", version = "v1", status)]``
- `#[derive(Metadata)]` -> creates `impl k8s_openapi::Metadata for Foo`
   * requiring that the previous derive is there (due to trait hierarchy)
- `#[derive(CrDefinition)]` -> creates `Foo::crd` method so people don't have to manage it
  * which, judging by code quality would be the most unstable one (but least necessary)
  * allowing `#[crd(subresource_scale = "{}")]` + `#[crd(printercolumn = "{}")]`

I also kind of want to be able to have the inline json stuff be replaced with something less horrible... just don't know what.

**Comment by teozkr** [comment]
Not sure what the use case is for deriving `CustomResource` but not `Metadata`, but :+1: on splitting out the CRD generation (at least while it's unstable).

**Comment by clux** [comment]
Yeah true.

Though having them combined gives the extra benefit of not being able to set the status subresource in only one of the resource and definition.

**Comment by clux** [comment]
Don't think I'll do too much more to this other than add some tests. Splitting it requires a double status arg. The rawstrings in the macros made it kind of acceptable I think (lacking better options).

Extra features like compile time schema validation and validation props can be done later. Schema validation is probably another proc_macro on its own.

**Pull request merged**
