### PR TITLE
Use id-token for oidc Authentication Provider

### PR DESCRIPTION
**Pull request by twz123**
This basically restores the functionality that has been added in #70. Same caveats apply here: auto-refresh of expired id-token is not supported.

### CODE REVIEW

**Review by kazk — COMMENTED** [review]
Thanks. I had overlooked `oidc` support when refactoring..

Do you think you can make this fit in the existing code?

Move this in `token_from_provider` by adding `ProviderToken::Oidc` variant and matching that like `gcp`. If not, I can do it in a separate PR.

**Comment by twz123** [comment]
Will do :+1:

**Review by kazk — APPROVED** [review]
Looks good to me. Thanks!

**Comment by clux** [comment]
released in 0.50.1

**Pull request merged**
