### PR TITLE
Load namespace when run in a cluster

### LINKED ISSUE #69: Retrieve the default namespace when running in cluster
It's [documented](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#accessing-the-api-from-a-pod) to be in `/var/run/secrets/kubernetes.io/serviceaccount/namespace`.

Perhaps this could be surfaced somehow?

### PR DESCRIPTION
**Pull request by dylanhart**
Fixes #69

### CODE REVIEW

**Comment by dylanhart** [comment]
CI failure looks to be an existing config issue?

```
# No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to get started with your configuration.
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
```

**Comment by clux** [comment]
Hey, thanks a lot for doing this. Not sure what the CI failure was, but updated your branch and it now seems to fail legitimately.

**Comment by dylanhart** [comment]
Whoops! forgot to push a fixup commit earlier.

**Comment by dylanhart** [comment]
oh shoot.. I killed your changes...

**Comment by clux** [comment]
Np. Was just a branch merge :-)

**Pull request merged**
