### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by davidB**
- Update dependencies version (no change in code)
- Add configuration for [dependabot](https://github.com/marketplace/dependabot-preview) a useful service to received PR for update of version (I use it for my OSS project). The service was recently acquired by GitHub iirc.

### CODE REVIEW

**Comment by davidB** [comment]
The CI failed is caused by "Plan Error":
```
#!/bin/sh -eo pipefail
# This job has been blocked because resource-class:large is not available on your plan. Please upgrade to continue building. Note: you will need to push a new commit or call the API to rerun the pipeline.
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
```

Can someone check ?

**Comment by clux** [comment]
I guess the `large` class is now an error to use :/

**Comment by clux** [comment]
I took most of the upgrades and applied them manually. Don't think I could deal with daily prs for this, but have upgraded all deps except `dirs` which had a major, unnecessary change.

**Comment by davidB** [comment]
More info about dependabot:
- it doesn't create a daily PR, it's not a spammer
- it checks daily if there is some dependencies update, then create one PR per dependencies and version (the frequency can be configured)
- if there is already  a PR for a previous version, then it close the previous one
- it provide some command (via comment like, ignore this version, ignore this dependencies,...)
- PR's comment try to follow project convention (in my case I use gitmoji, so PR have gitmoji)

As an example you can look at https://github.com/davidB/kubectl-view-allocations/pull/2 (I'll merge it later)

IMHO, it's a very good assistant to keep project's dependencies uptodate and to know which dependencies's update break the code or note (see: https://github.com/davidB/git-find/pulls?utf8=%E2%9C%93&q=is%3Apr+dependabot+) and to have history of update vs a commit with a batch of change like this one.

**Pull request closed without merging**
